name: Setup

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_personalize:
    name: Personalize
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install prerequisites
        run: |
          pip install -r setup-requirements.txt

      - name: Run personalize script
        run: |
          python scripts/personalize.py --github-org epwalsh --github-repo new-repo --package-name new-package --yes

      - name: Verify changes
        shell: bash
        run: |
          set -eo pipefail
          grep -q 'new-package' setup.py .github/workflows/main.yml CONTRIBUTING.md
          grep -q 'https://github.com/epwalsh/new-repo' setup.py CONTRIBUTING.md
          if [[ grep -q 'my-package' setup.py CONTRIBUTING.md ]]; then
            echo "Found 'my-package' where it shouldn't be"
            exit 1
          fi
